[build]
  command = "npm run build:production"
  publish = "build"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  REACT_APP_DEPLOYMENT_ENV = "production"

# SPA redirects - CRITICAL for React routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Pi Browser specific headers - More permissive
[[headers]]
  for = "/*"
  [headers.values]
    # Remove restrictive frame options for Pi Browser
    X-Frame-Options = "ALLOWALL"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Pi Browser compatibility headers
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    
    # Very permissive CSP for Pi Browser compatibility
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https: data: blob:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https: data:; style-src 'self' 'unsafe-inline' https: data:; img-src 'self' https: data: blob:; connect-src 'self' https: wss: data:; frame-src 'self' https:; font-src 'self' https: data:; object-src 'none'; base-uri 'self'; form-action 'self' https:;"

# Alternative even more permissive headers for testing
[[headers]]
  for = "/test/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:;"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "*"

# Optimize static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Font caching
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Pi SDK caching
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Access-Control-Allow-Origin = "*"

# Production context
[context.production]
  command = "npm run build:production"
  [context.production.environment]
    REACT_APP_DEPLOYMENT_ENV = "production"
    REACT_APP_ENABLE_DEBUG_MODE = "false"
    GENERATE_SOURCEMAP = "false"

# Development context  
[context.development]
  command = "npm run build"
  [context.development.environment]
    REACT_APP_DEPLOYMENT_ENV = "development"
    REACT_APP_ENABLE_DEBUG_MODE = "true"

# Deploy previews
[context.deploy-preview]
  command = "npm run build"
  [context.deploy-preview.environment]
    REACT_APP_DEPLOYMENT_ENV = "preview"
