[build]
  command = "npm run build:production"
  publish = "build"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  REACT_APP_DEPLOYMENT_ENV = "production"

# SPA redirects - CRITICAL for React routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Fixed CSP with all required Firebase and Pi domains
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Fixed CSP with complete Firebase domains
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://sdk.minepi.com https://blockstream.info https://www.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://firebase.googleapis.com https://firestore.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com https://blockstream.info https://sdk.minepi.com https://socialchain.app wss://*.firebaseio.com wss://*.web.app; frame-src 'none'; object-src 'none'; base-uri 'self'; form-action 'self';"

# Optimize static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Font caching
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Pi SDK caching
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Production context
[context.production]
  command = "npm run build:production"
  [context.production.environment]
    REACT_APP_DEPLOYMENT_ENV = "production"
    REACT_APP_ENABLE_DEBUG_MODE = "false"
    GENERATE_SOURCEMAP = "false"

# Development context  
[context.development]
  command = "npm run build"
  [context.development.environment]
    REACT_APP_DEPLOYMENT_ENV = "development"
    REACT_APP_ENABLE_DEBUG_MODE = "true"

# Deploy previews
[context.deploy-preview]
  command = "npm run build"
  [context.deploy-preview.environment]
    REACT_APP_DEPLOYMENT_ENV = "preview"
